- name: "Ensure '{{ nfs_server_service_name }}' service is enabled to start at boot: {{ status }}"
  ansible.builtin.service:
    name: "{{ nfs_server_service_name }}"
    enabled: "{{ status }}"
  vars:
    status: "{{ en_v3 or en_v4 }}"
  become: true
  become_user: root

- name: "Ensure '{{ nfs_server_service_name }}' service is {{ status }}"
  ansible.builtin.service:
    name: "{{ nfs_server_service_name }}"
    state: "{{ status }}"
  vars:
    status: "{{ 'started' if (en_v3 or en_v4) else 'stopped' }}"
  become: true
  become_user: root
  changed_when: false

- name: "Ensure '{{ nfs_server_mapping_service_name }}' service is enabled to start at boot: {{ status }}"
  ansible.builtin.service:
    name: "{{ nfs_server_mapping_service_name }}"
    enabled: "{{ status }}"
  vars:
    status: "{{ (en_v3 or en_v3) and nfs_server_nfsv4_enable_useratdomain_mapping_service }}"
  become: true
  become_user: root

- name: "Ensure '{{ nfs_server_mapping_service_name }}' service is {{ status }}"
  ansible.builtin.service:
    name: "{{ nfs_server_mapping_service_name }}"
    state: "{{ status }}"
  vars:
    status: "{{ 'started' if ((en_v3 or en_v3) and nfs_server_nfsv4_enable_useratdomain_mapping_service) else 'stopped' }}"
  become: true
  become_user: root
  changed_when: false

