- name: "Ensure all NFS services are enabled or disabled to start at boot, as required"
  ansible.builtin.service:
    name: "{{ setting.nm }}"
    enabled: "{{ setting.st }}"
  loop:
    - { nm: "{{ nfs_server_service_name }}", st: "{{ en_v3 or en_v4 }}" }
    - { nm: "{{ nfs_server_mapping_service_name }}",
        st: "{{ en_v4 and nfs_server_nfsv4_enable_useratdomain_mapping_service }}" }
  loop_control:
    loop_var: setting
  become: true
  become_user: root

- name: "Ensure all NFS services are started or stopped, as required"
  ansible.builtin.service:
    name: "{{ setting.nm }}"
    state: "{{ 'started' if setting.st else 'stopped' }}"
  loop:
    - { nm: "{{ nfs_server_service_name }}", st: "{{ en_v3 or en_v4 }}" }
    - { nm: "{{ nfs_server_mapping_service_name }}",
        st: "{{ en_v4 and nfs_server_nfsv4_enable_useratdomain_mapping_service }}" }
  loop_control:
    loop_var: setting
  become: true
  become_user: root

