# version support for various NVFS versions
nfs_server_enable_nfsv3: false
nfs_server_enable_nfsv4: true

# for NVSv4, enable a service to map user@domain (received from NFS client)
# to UIDs and GIDs (on the NFS server's filesystem)
nfs_server_nfsv4_enable_useratdomain_mapping_service: true

# for NVSv4, increase performance by allowing client to manipulate file locally
nfs_server_nfsv4_enable_client_delegations: true

# for NVSv4, allow the NFS server to lock (i.e. access) the data in NFS shares
nfs_server_nfsv4_enable_server_nfs_share_locking: false

